#!/usr/bin/env bash
# Install HAproxy
apt-get update -y
apt-get install haproxy -y

config="
frontend front_end
	bind *:80
	default_backend back_end

backend back_end
	balance roundrobin
	server 149870-web-01 100.25.147.62 check
	server 149870-web-02 54.174.169.156 check"

echo "$config" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
