#!/usr/bin/env bash
# Make nginx run on port 80 and restart service
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep nginx | head -1)"
