#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=10
while [ "$i" -gt 0 ]
do
	if [ "$i" -eq 7 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 3 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i--))
done
