#!/usr/bin/env bash
# Configures an ubuntu server
hosts=/etc/hosts
tmp="hosts.tmp"
cp "$hosts" "$tmp"
if grep -q "localhost" "$tmp"
then
	sed -i "s/^.*localhost$/127.0.0.1\tlocalhost/" "$tmp"
else
	sed -i '$a\127.0.0.1 localhost/' "$tmp"
fi
sed -i '$a\8.8.8.8 facebook.com' "$tmp"
mv -f "$tmp" "$hosts"
