#!/usr/bin/env bash
# Configures an ubuntu server
hosts=/etc/hosts
if grep -q "localhost" "$hosts"
then
	sed -i "s/^.*localhost$/127.0.0.2\tlocalhost/" "$hosts"
else
	sed -i '$a\127.0.0.2 localhost/' "$hosts"
fi
sed -i '$a\8.8.8.8 facebook.com' "$hosts"
